answer_mapping = {
            "man": ["men", "man", "person", "people"],
            "bicycle": ["bicycles", "bicycle", "bike", "bikes"],
            "car": ["cars", "car"],
            "motorcycle": ["motorcycles", "motorcycle", "bike", "bikes"],
            "airplane": ["airplanes", "plane", "planes", "airplane"],
            "bus": ["buses", "bus"],
            "train": ["trains", "train"],
            "truck": ["trucks", "truck"],
            "boat": ["boats", "boat"],
            "traffic light": ["traffic lights", "traffic light"],
            "fire hydrant": ["fire hydrants", "hydrant", "fire hydrant"],
            "stop sign": ["stop signs", "stop sign"],
            "parking meter": ["parking meters", "parking meter"],
            "bench": ["benches", "bench"],
            "bird": ["birds", "bird"],
            "cat": ["cats", "cat"],
            "dog": ["dogs", "dog"],
            "horse": ["horses", "horse"],
            "sheep": ["sheep"],
            "cow": ["cows", "cow"],
            "elephant": ["elephants", "elephant"],
            "bear": ["bears", "bear"],
            "zebra": ["zebras", "zebra"],
            "giraffe": ["giraffes", "giraffe"],
            "backpack": ["backpacks", "backpack"],
            "umbrella": ["umbrellas", "umbrella"],
            "handbag": ["handbags", "handbag"],
            "tie": ["ties", "tie"],
            "suitcase": ["suitcases", "suitcase"],
            "frisbee": ["frisbees", "frisbee"],
            "skis": ["skis", "ski"],
            "snowboard": ["snowboards", "snowboard"],
            "sports ball": ["sports balls", "sports ball", "ball", "balls"],
            "kite": ["kites", "kite"],
            "baseball bat": ["baseball bats", "bat", "baseball bat"],
            "baseball glove": ["baseball gloves", "glove", "baseball glove"],
            "skateboard": ["skateboards", "skateboard"],
            "surfboard": ["surfboards", "surfboard"],
            "tennis racket": ["tennis rackets", "racket", "tennis racket"],
            "bottle": ["bottles", "bottle"],
            "wine glass": ["wine glasses", "glass", "wine glass"],
            "cup": ["cups", "cup"],
            "fork": ["forks", "fork"],
            "knife": ["knives", "knife"],
            "spoon": ["spoons", "spoon"],
            "bowl": ["bowls", "bowl"],
            "banana": ["bananas", "banana"],
            "apple": ["apples", "apple"],
            "sandwich": ["sandwiches", "sandwich"],
            "orange": ["oranges", "orange"],
            "broccoli": ["broccoli"],
            "carrot": ["carrots", "carrot"],
            "hot dog": ["hot dogs", "hotdog", "hot dog"],
            "pizza": ["pizzas", "pizza"],
            "donut": ["donuts", "doughnuts", "donut", "doughnut"],
            "cake": ["cakes", "cake"],
            "chair": ["chairs", "chair"],
            "couch": ["couches", "sofa", "couch"],
            "potted plant": ["potted plants", "plant", "potted plant"],
            "bed": ["beds", "bed"],
            "dining table": ["dining tables", "table", "dining table"],
            "toilet": ["toilets", "toilet"],
            "tv": ["television", "tv", "tv set"],
            "laptop": ["laptops", "laptop"],
            "mouse": ["mice", "mouse"],
            "remote": ["remotes", "remote"],
            "keyboard": ["keyboards", "keyboard"],
            "cell phone": ["cell phones", "phone", "cellphone", "cell phone"],
            "microwave": ["microwaves", "microwave"],
            "oven": ["ovens", "oven"],
            "toaster": ["toasters", "toaster"],
            "sink": ["sinks", "sink"],
            "refrigerator": ["refrigerators", "fridge", "refrigerator"],
            "book": ["books", "book"],
            "clock": ["clocks", "clock"],
            "vase": ["vases", "vase"],
            "scissors": ["scissors"],
            "teddy bear": ["teddy bears", "teddy", "teddy bear"],
            "hair drier": ["hair dryers", "hair drier", "hair dryer"],
            "toothbrush": ["toothbrushes", "brush", "toothbrush"]
        }